version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:5000
    volumes:
      - .:/app
    networks:
     - v2v_network
networks:
 v2v_network:
   driver: bridge
